"""Generate the machine-readable tool manifest and the tool reference docs.

Reads live registry metadata (single source of truth — never hand-edited):

  python scripts/generate_tool_manifest.py

Outputs:
  docs/tools_manifest.json — every tool with schema, deps, costs, units
  docs/TOOLS.md            — human reference grouped by category
"""

from __future__ import annotations

import json
import sys

sys.path.insert(0, ".")


def main() -> None:
    from agent.tools.registry import build_tool_registry

    reg = build_tool_registry()
    tools = [reg.get(n).metadata() for n in reg.names()]
    for tool, name in zip(tools, reg.names()):
        tool["schema"] = reg.get(name).parameters

    with open("docs/tools_manifest.json", "w", encoding="utf-8") as fh:
        json.dump({"tool_count": len(tools), "tools": tools}, fh, indent=2)

    by_category: dict = {}
    for tool in tools:
        by_category.setdefault(tool["category"], []).append(tool)

    lines = ["# Tool reference", "",
             f"{len(tools)} tools across {len(by_category)} categories. "
             "Generated by `scripts/generate_tool_manifest.py` — do not edit by hand.",
             ""]
    for category in sorted(by_category):
        lines += [f"## {category} ({len(by_category[category])})", ""]
        lines += ["| tool | description | required args | network | needs extra deps |",
                  "|---|---|---|---|---|"]
        for tool in by_category[category]:
            req = ", ".join(tool["required"]) or "—"
            net = "yes" if tool["network"] else "—"
            deps = ", ".join(tool["requires"]) or "—"
            desc = tool["description"].replace("|", "/")
            lines.append(f"| `{tool['name']}` | {desc} | {req} | {net} | {deps} |")
        lines.append("")
    lines += ["## Composability",
              "",
              "Tools consume GeoJSON FeatureCollections, tables, rasters (file "
              "descriptors), networks, or coordinates, and return typed envelopes "
              "(`ok`, `type`, payload, `crs`, metadata). Intermediate results "
              "chain through `$step_id` references resolved by the orchestrator; "
              "large payloads never enter the LLM prompt (summaries only).",
              "",
              "## Mock / live behaviour",
              "",
              "ArcGIS datasets serve mock fixtures while `ARCGIS_USE_MOCK=true`, "
              "flagged `mocked: true` with `provisional_schema: true` and the "
              "real `live_urls`. Provider tools (Overpass, Nominatim, Open-Meteo, "
              "GBIF, STAC, WFS) need network and fail with explicit capability "
              "errors when unreachable.",
              ""]
    with open("docs/TOOLS.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"{len(tools)} tools -> docs/tools_manifest.json + docs/TOOLS.md")


if __name__ == "__main__":
    main()
